function cockandballs() {
    var messages = [
        `i dont know what im doing anymore!`,
        `okay ❤ yay ❤`,
        `toki a!`,
        `I'm. ‎ ‎ ‎crashing thhe fuck out!!`,
        `what else do i write here`,
        `🌙`,
        `over the moon...`,
        `🌙`,
        `subscribe to technoblade`,
        `BLOOD FOR THE BLOOD GOD`,
        `technoblade never dies`,
        `umop-apisdn`,
        `pretend this is a funny joke and laugh please`,
        `hello vro`,
        `...`,
        `is funkinosc v2 out yet?!`,
        `/imc`,
        `now with less serotonin!`,
        `wega board`,
        `it's not a making day.`,
        `artist lemonade!`,
        `irrelevant!`,
        `apathy`,
        `it starts with ONE- *ONE intro plays*`,
        `stay hydrated`,
        `dawg what the fuck`,
        `meeeee :3`,
        `:3`,
        `i do NOT want the poo poo platter.`,
        `I'm tired boss.`,
        `PUKEKO BIRD`,
        `totally real placeholder text`,
        `WAWA!!!!!!!`,
        `they should invent a brain that doesnt tell you mean things everday`,
        `his greed sickens me`,
        `ILL MAKE YOU SAY HOW PROUD YOU ARE OF ME<br>SO STAY AWAKE JUST LONG ENOUGH TO SEE<br>MY WAY`,
        `oo yeah ha-ha!`,
        `you've been here for as long as you can remember`,
        `insults for tall people`,
        `cant draw straight lines!`,
        `what the hell is that fruit passionate about`,
        `good morning jpeggers`,
        `glbglbglb`,
        `may your woes be many and your days few`,
        `<span class="vcr">Judgement!</span>`,
        `<span class="vcr">Thy end is now!</span>`,
        `0_0 That. Is. Epic`,
        `Goated`,
        `play webfishing!`,
        `got that fog in me`,
        `the voices are getting louder`,
        `blahaj`,
        `thinking about someone...`,
        `hello world`,
        `find my voice - although it sounds like bits and bytes`,
        `your local twink ass android thats also a walking and talking crt tv`,
        `pink and orange skies are nice`,
        `sosig`,
        `silly, dimwitted even`,
        `i am the opposite of artificial intelligence<br>i am genuine stupidity`,
        `mispellde`,
        `remember, it's cognitive behavioural therapy!`,
        `beef or chicken`,
        `nocturne e major`,
        `fruitiger aero!`,
        `still a nobody!`,
        `romantically steals some of your organs`,
        `avoids using 'ur' and 'u' to sound cooler!`,
        `saddam hussein hiding spot`,
        `didja add 3 instances of OTT with 6 Soundgoodizers in your songs yet?`,
        `that femboy drawing of me is not real.`,
        `consider the following`,
        `hey hey. check this out. balls`,
        `how do you wear a hoodie/jacket? standard or gay`,
        `bagel`,
        `it's peam`,
        `good lord theres penice`,
        `backshot roulette`,
        `evil kommit be like: i HATE silly billy`,
        `how many times have you refreshed or clicked me at this point?`,
        `you love sonic frontiers?`,
        `i am either yapping or napping`,
        `these bitches gay! good for them. good for them`,
        `Lober`,
        `<span class="determination">HOW DO YOU FEEL ABOUT YOUR CREATION? (IT WILL NOT HEAR.)</span>`,
        `nikku`,
        `listen to the art of war by chipzel!`,
        `please pull the plug`,
        `i ate a burger`,
        `oddly irrelevant!`,
        `roo beer no`,
        `*sigh* bapanada`,
        `is silksong out yet...`,
        `im tired`,
        `way past cool`,
        `tails get off the lankybox`,
        `The kommit Situation Is Crazy`,
        `freakbob`,
        `i miss vc lobotomies`,
        `brain damage`,
        `<span class="determination">But it refused.</span>`,
        `<span class="determination">* Don't you have anything better to do?</span>`,
        `1 ATK 5 DEF`,
        `oog`,
        `amen breaks!`,
        `challenge soon`,
        `(inside joke)`,
        `ssddfgfhdghgfdsfdfhfdkh`,
        `this is gonna leave a-<br>markiplier: a what?`,
        `an empty bliss beyond this world`,
        `it's just a burning memory`,
        `cowabummer!`,
        `gadzooks`,
        `"if i send this void away, have i lost a part of me?"`,
        `splash text!`,
        `hi`,
        `i wasted so much time on this`,
        `is there any meaning to this`,
        `<span class="vcr">THE WORLD LOOKS RED</span>`,
        `how queer`,
        `head empty`,
        `lets play hide and seek! you hide, i seek professional help`,
        `dysfunctional for 6 years and counting`,
        `rawdoggin life`,
        `chickne snaddich`,
        `lightspeed is easier :3`,
        `t-spin!`,
        `&lt;p&gt;i totally know what im doing!&lt;/p&gt;`,
        `i wish i was good enough`,
        `more than 130 splashes!`,
        `it's a beautiful day outside.`,
        `<span class="vcr=>MANKIND IS DEAD.<br>BLOOD IS FUEL.<br>HELL IS FULL.</span>`,
        `yapper!`,
        `The Title Only For People Who Caught The Super Duper Rare Golden Bass Title`,
        `SITELEN TAWA SEWI`,
        `burn my dreaddd`,
        `Time never waits.<br>It delivers is all equally to the same end.`,
        `do NOT mention it ever`,
        `cryign sobbign rn`,
        `a fool, perhaps!`,
        `an idiot, i think!`,
        `placin blocks!`,
        `i am placin blocks n shit cus im in fuckin minecrafttt`,
        `not family friendly!`,
        `that's crazy`,
        `<span class="dealer">Now, me and you, we are dancing on the edge of life and death.<br><br>Are you ready?</span>`,
        `uscore?`,
        `so, back in the day- jingle jingle jingle, back in the day, BEFORE the backrooms were a thing? okay? pay att- jingle jingle pay attention j- pay attention i said your favourite word!`,
        `acoustic`,
        `slowly running out of things to write here`,
        `i think i spent 3 hours on the stupid notepad toggle in artchive`,
        `erm what the freak`,
        `not safe for wo- *falls off office chair*`,
        `oh shit i got cyberbullied`,
        `e-girls? e-boys? i just want to be e-nough`,
        `i should add a splash text click counter...`,
        `end this, now!`,
        `don't forget, i'm with you in the dark`,
        `cheesy! (hfj?)`,
        `<span class="determination">Potassium</span>`,
        `moss`,
        `cats!`,
        `these birds are pissing me off`,
        `im the original starwalker`,
        `the`,
        `egg`,
        `i am NOT a furry`,
        `I AM NOT A FEMBOY!!!!!`,
        `NO WAY? NO WAY! NO WAY? NO WAY! NO WAY? NO WAY!`,
        `<span class="determination">DEALS SO GOOD I [$%?!] MYSELF</span>`,
        `my wife sneezes twice`,
        `shaw!`,
        `line <br>eak!`,
        `<span class="utpapyrus">nyeh heh heh!</span>`,
        `batermy acid`,
        `<span class="determination">Noelle Sweetie Honey Darling Gravy</span>`,
        `<span class="determination">* The wind is howling...</span>`,
        `<span class="utsans">* take of yourself kid, 'cause someone really cares about you.</span>`,
        `<span class="determination">despite everything, it's still you</span>`,
        `<span class="determination">damn, didn't get to impale myself...</span>`,
        `<span class="determination">Teens Are Merely Big Children (And Adults Are Bigger Children)</span>`,
        `<span class="determination">You Don't Do Crazy Things Like Have Opinions</span>`,
        `<span class="determination">WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT?</span>`,
        `<span class="determination">stop everything. [user], get the banana</span>`,
        `<span class="determination">i was simply relaxing in kris' spacious pants hole</span>`,
        `<span class="determination">I Only Play Mobile Games</span>`,
        `<span class="determination">* The power of mean girls shines within you.</span>`,
        `<span class="determination">* The power of fluffy boys shines within you.</span>`,
        `<span class="dealer">PLEASE SIGN THE WAIVER.</span>`,
        `<span class="dealer">Long last, we arrive at the final showdown.</span>`,
        `<span class="determination">You Are Going To Kick: My Ass</span>`,
        `<span class="determination">Self Esteem Eradication Complete (Initiating Laughing Procedure)</span>`,
        `<span class="determination">Whoops That Was My Extra Dangerous Glass</span>`,
        `<span class="determination">I Have No Time For Such Frivolities (And Would Kick Your Ass)</span>`,
        `<span class="determination">Step one: I thrash you. Step two: you lose.</span>`,
        `<span class="determination">I Am Going To Be Your Wacky Roommate Now</span>`,
        `<span class="determination">(Life cannot exist without consuming.)<br>(Even the moss drinks water.)<br>(Perpetuate the cycle of existence?)</span>`,
        `<span class="determination">* HEY      EVERY     !! IT'S ME!!!</span>`,
        `<span class="dealer">1 LIVE, 1 BLANK. WILL YOU TAKE THE SHOT?</span>`,
        `<span class="vcr">+ RICOSHOT</span>`,
        `<span class="omori">OMORI did not succumb.</span>`,
        `<span class="omori">I fucking love air-conditioning.</span>`,
        `<span class="omori">Eternal banana.</span>`,
        `<span class="omori">My thoughts will follow you into your dreams.</span>`,
        `<span class="omori">i omor<br><br>- very real quote from the game</span>`,
        `<span class="omori">i got burgers on my mind</span>`,
        `<span class="determination">CONGRULATIONS YOU ARE THE 100th VISITOR!!! CLICK HERE TO [Die]</span>`,
        `<span class="determination">ARE YOU THERE?<br>ARE WE CONNECTED?</span>`,
        `<span class="determination">YOU ACKNOWLEDGE THE POSSIBILITY OF PAIN AND SEIZURE.</span>`,
        `<span class="omori">Welcome to WHITE SPACE.</span>`,
        `<span class="omori">You've been living here as long as you can remember.</span>`,
        `<span class="determination">no controlli is cannoli</span>`,
        `<span class="determination">CHAOS, CHAOS! I CAN DO ANYTHING!</span>`,
        `<span class="determination">GOD<br><br>DAMN IT</span>`,
        `<span class="determination">Self-Esteem Eradication Complete<br>Running Laughing Protocol</span>`,
        `<span class="determination">* (You weren't tall or strong enough to use the controls...)</span>`,
        `<span class="determination">Preference Settings Set To "Perish"</span>`,
        `<span class="determination">Kris Cross Applesauce</span>`,
        `<span class="determination">I Love Tolerating You</span>`,
        `<span class="determination">meowowme<br>owowowow</span>`,
        `<span class="determination">* You unconsciously clicked on a popup about "monsters 4 humans" "in your area,</span>`,
        `the cycle continues...`,
        `eat moss!`,
        `no double trucies!`,
        `died to berdly's fight!`,
        `wega board`,
        `Proceed.`,
        `listen to queen's mixtape!`,
        `do not interact with lancer's portraits in the card castle!`,
        `level 2 bed inspector!`,
        `in your walls!`,
        `no-clipped!`,
        `<span class="determination">* Ah, Kris... NOT the lifeform I was looking for.</span>`,
        `minos crime`,
        `ultrakrill!`,
        `flamingo!`,
        `you're finally awake`,
        `the code is a mess`,
        `GIAEEFSBISSFLBALAELRHEIGSFFEBRSI`,
        `mortal kombat on hardcore is impossible`,
        `beep boop`,
        `no longer obsessed over fnf!`,
        `a manor. mansion. mrmmm.`,
        `if humans had tails, we'd probably find unique ways to use them`,
        `oh no way we got that fanta made of glass`,
        `i cant get the mewing horse out of my head, i need to be saved`,
        `bestie is ur stovetop powered by the fucking sun`,
        `you cant just write perchance`,
        `eating chalk!`,
        `try to guess my favourite deltarune ch2 character challenge (impossible)`,
        `drinking the eminem potion at 3am`,
        `no motivation!`,
        `gregory have you played among us before`,
        `what the hell why are game characters talking in the splash text now tf`,
        `fl studio!`,
        `fruity loops`,
        `open source?`,
        `plays solitaire!`,
        `windows 7!`,
        `fishing in the void!`,
        `socially inept!`,
        `tip: if you ignore it, maybe it will go away`,
        `fish fear me`,
        `yet another generic website!`,
        `below average code!`,
        `cornflowers are cool`,
        `blue orchids are also pretty cool`,
        `colon three`,
        `also play buckshot roulette!`,
        `silly billy!`,
        `please enjoy these sites equally`,
        `SF 482719548284621732345446827354258476354761922487665745.6`,
        `scatterbrain`,
        `STONE 713864950843883218972158619580770734586267510478086528132279435.1`,
        `AIRY 48378956413610815174867455100523523993246453827549716928.3`,
        `you move, i send`,
        `otters are cute`,
        `cool text`,
        `balls`,
        `nuts, even`,
        `real`,
        `hold up his writing is this fire?!`,
        `50k`,
        `click me!`,
        `im an anomalocaris! i do my best`,
        `<img src="kije.png" alt="kijetesantakalu" width="50">`,
        `still procrastinating`,
        `bedrotting`,
        `aye aye captain`,
        `i have a lot of projects and im doing none of them`,
        `im bomeless`,
        `Dbumnass`,
        `starways!`,
        `interaction bait`,
        `would your pfp help an old lady across the road be honest!`,
        `DAMN!!!!!!!!!!!!!!!!!!!!!!!!!!!`,
        `the you you are`,
        `sina li jaki e lawa`,
        `i should really start taking learning it more seriously`,
        `liar liar pants on fire`,
        `chicken butt`,
        `imagine i put an arg here jkjk unless`,
        `if the text suddenly disappears its probably some bug in the javascript mb gang`,
        `for what purpose???`,
        `emphasis!!!!!!!`,
        `also play powerwash simulator`,
        `#19`,
        `missing`,
        `busting (a move)`,
        `blue!`,
        `jan pi kiwen mun`,
        `starstruck!`,
        `:point_left: :point_right:`,
        `stop procrastinating bro`,
        `read if cool`,
        `after pride month, all gays must return to mother earth`,
        `butter dog`,
        `https://www.youtube.com/watch?v=Oc4_Ex9Hdg4`,
        `"quicken my demise, cus im a homo writin gay rhymes!"`,
        `how can i type faster on phone`,
        
    ];
    //  `text`,
    //  `<span class="determination">DETERMINATIONTEXT</span>`,
    //  `<span class="utsans">UNDERTALESANSTEXT</span>`,
    //  `<span class="utpapyrus">UNDERTALEPAPYRUSTEXT</span>`,
    //  `<span class="comicsans">COMICSANSMSTEXT</span>`,
    //  `<span class="dealer">BUCKSHOTROULETTEDEALERTEXT</span>`,
    //  `<span class="vcr">VCRULTRAKILLTEXT</span>`,
    //  `<span class="omori">OMORITEXT</span>`,


    var rText = Math.floor(Math.random() * messages.length);
    
    document.getElementById("randomsplash").innerHTML = messages[rText];


    const clickSplash = document.getElementById("randomsplash");

    clickSplash.addEventListener("click", function() {
        var rText = Math.floor(Math.random() * messages.length);
        document.getElementById("randomsplash").innerHTML = messages[rText];
    });
}

cockandballs();
//  please laugh