function cockandballs() {
    var messages = [
        `i dont know what im doing anymore!`,
        `okay ❤ yay ❤`,
        `toki a!`,
        `I'm. ‎ ‎ ‎crashing thhe fuck out!!`,
        `what else do i write here`,
        `🌙`,
        `over the moon...`,
        `🌙`,
        `subscribe to technoblade`,
        `BLOOD FOR THE BLOOD GOD`,
        `technoblade never dies`,
        `umop-apisdn`,
        `pretend this is a funny joke and laugh please`,
        `hello vro`,
        `...`,
        `is funkinosc v2 out yet?!`,
        `/imc`,
        `now with less serotonin!`,
        `wega board`,
        `it's not a making day.`,
        `artist lemonade!`,
        `irrelevant!`,
        `apathy`,
        `it starts with ONE- *ONE intro plays*`,
        `stay hydrated`,
        `dawg what the fuck`,
        `meeeee :3`,
        `:3`,
        `i do NOT want the poo poo platter.`,
        `I'm tired boss.`,
        `PUKEKO BIRD`,
        `totally real placeholder text`,
        `WAWA!!!!!!!`,
        `they should invent a brain that doesnt tell you mean things everday`,
        `his greed sickens me`,
        `ILL MAKE YOU SAY HOW PROUD YOU ARE OF ME<br>SO STAY AWAKE JUST LONG ENOUGH TO SEE<br>MY WAY`,
        `oo yeah ha-ha!`,
        `you've been here for as long as you can remember`,
        `insults for tall people`,
        `cant draw straight lines!`,
        `what the hell is that fruit passionate about`,
        `good morning jpeggers`,
        `glbglbglb`,
        `may your woes be many and your days few`,
        `judgement!`,
        `thy end is now!`,
        `0_0 That. Is. Epic`,
        `Goated`,
        `play webfishing!`,
        `got that fog in me`,
        `the voices are getting louder`,
        `blahaj`,
        `thinking about someone...`,
        `hello world`,
        `find my voice - although it sounds like bits and bytes`,
        `your local twink ass android thats also a walking and talking crt tv`,
        `pink and orange skies are nice`,
        `sosig`,
        `silly, dimwitted even`,
        `i am the opposite of artificial intelligence<br>i am genuine stupidity`,
        `mispellde`,
        `remember, it's cognitive behavioural therapy!`,
        `beef or chicken`,
        `nocturne e major`,
        `fruitiger aero!`,
        `still a nobody!`,
        `romantically steals some of your organs`,
        `avoids using 'ur' and 'u' to sound cooler!`,
        `saddam hussein hiding spot`,
        `didja add 3 instances of OTT with 6 Soundgoodizers in your songs yet?`,
        `that femboy drawing of me is not real.`,
        `consider the following`,
        `hey hey. check this out. balls`,
        `how do you wear a hoodie/jacket? standard or gay`,
        `bagel`,
        `it's peam`,
        `good lord theres penice`,
        `backshot roulette`,
        `evil kommit be like: i HATE silly billy`,
        `how many times have you refreshed at this point?`,
        `you love sonic frontiers?`,
        `i am either yapping or napping`,
        `these bitches gay! good for them. good for them`,
        `Lober`,
        `HOW DO YOU FEEL ABOUT YOUR CREATION? (IT WILL NOT HEAR.)`,
        `nikku`,
        `listen to the art of war by chipzel!`,
        `please pull the plug`,
        `i ate a burger`,
        `oddly irrelevant!`,
        `roo beer no`,
        `*sigh* bapanada`,
        `is silksong out yet...`,
        `im tired`,
        `way past cool`,
        `tails get off the lankybox`,
        `The kommit Situation Is Crazy`,
        `freakbob`,
        `i miss vc lobotomies`,
        `brain damage`,
        `But it refused.`,
        `* Don't you have anything better to do?`,
        `1 ATK 5 DEF`,
        `oog`,
        `amen breaks!`,
        `challenge soon`,
        `<inside joke>`,
        `ssddfgfhdghgfdsfdfhfdkh`,
        `this is gonna leave a-<br>markiplier: a what?`,
        `an empty bliss beyond this world`,
        `it's just a burning memory`,
        `cowabummer!`,
        `gadzooks`,
        `"if i send this void away, have i lost a part of me?"`,
        `splash text!`,
        `hi`,
        `i wasted so much time on this.`,
        `is there any meaning to this`,
        `THE WORLD LOOKS RED`,
        `how queer`,
        `head empty`,
        `lets play hide and seek! you hide, i seek professional help`,
        `dysfunctional for 6 years and counting`,
        `rawdoggin life`,
        `chickne snaddich`,
        `lightspeed is easier :3`,
        `t-spin!`,
        `&lt;p&gt;i totally know what im doing!&lt;/p&gt;`,
        `i wish i was good enough`,
        `more than 130 splashes!`,
        `it's a beautiful day outside.`,
        `MANKIND IS DEAD. BLOOD IS FUEL. HELL IS FULL.`,
        `yapper!`,
        `The Title Only For People Who Caught The Super Duper Rare Golden Bass Title`,
        `SITELEN TAWA SEWI`,
        `burn my dreaddd`,
        `Time never waits.<br>It delivers is all equally to the same end.`,
        `do NOT mention it ever`,
        `line<br>break!`,
        `a fool, perhaps!`,
        `an idiot, i think!`,
        `placin blocks!`,
        `i am placin blocks n shit cus im in fuckin minecrafttt`,
        `not family friendly!`,
        `that's crazy`,
        `Now, me and you, we are dancing on the edge of life and death.<br><br>Are you ready?`,
        `uscore?`,
        `so, back in the day- jingle jingle jingle, back in the day, BEFORE the backrooms were a thing? okay? pay att- jingle jingle pay attention j- pay attention i said your favourite word!`,
        `acoustic`,
        `slowly running out of things to write here`,
        `i think i spent 3 hours on the stupid notepad toggle in artchive`,
        `erm what the freak`,
        `not safe for wo- *falls off office chair*`,
        `oh shit i got cyberbullied`,
        `e-girls? e-boys? i just want to be e-nough`,
        `the power of fluffy boys shines within you`,
        `the power of mean girls shines within you`,
        `don't forget, i'm with you in the dark`,
        `I Only Play Mobile Games`,
        `i was simply relaxing in kris' spacious pants hole`,
        `moss`,
        `stop everything. [user], get the banana`,
        `these birds are pissing me off`,
        `im the original starwalker`,
        `WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT?`,
        `Noelle Sweetie Honey Darling Gravy `,
        `the`,
        `egg`,
        `DEALS SO GOOD I [$%?!] MYSELF`,
        `You Don't Do Crazy Things Like Have Opinions`,
        `Teens Are Merely Big Children (And Adults Are Bigger Children)`,
        `shaw!`,
        `* The wind is howling...`
    //  `text`,
    ];

    var rText = Math.floor(Math.random() * messages.length);
    
    document.getElementById("randomsplash").innerHTML = messages[rText];


    const clickSplash = document.getElementById("randomsplash");

    clickSplash.addEventListener("click", function() {
        var rText = Math.floor(Math.random() * messages.length);
        document.getElementById("randomsplash").innerHTML = messages[rText];
    });
}

cockandballs();
//  please laugh